
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import pl.com.matematyka.db.Dzial;

public class DzialyPane extends javax.swing.JPanel {

    /**
     * Creates new form DzialyPane
     */
    private List<Dzial> dl;
    private int wybranyDzial = 0;
    private QuestionDialog parent = null;

    private class AwyborAction extends AbstractAction {
        private Dzial d;

        public AwyborAction(Dzial d) {
            this.d = d;
            putValue(NAME, d.getNazwa_dzialu());
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            wybranyDzial = d.getId_dzialu();
        }
    }

    public DzialyPane(List<Dzial> dl, QuestionDialog parent) {
        initComponents();
        this.dl = dl;
        this.parent = parent;
        ini();
    }

    private void ini() {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ButtonGroup bg = new ButtonGroup();
        for (Dzial dzial : dl) {
            JRadioButton rb = new JRadioButton(new AwyborAction(dzial));
            bg.add(rb);
            add(rb, gbc);
        }
        gbc.weighty = 1;
        add(new JPanel(), gbc);

        gbc.weighty = 0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.CENTER;

        JButton wyslijButton = new JButton("Wybierz");
        wyslijButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
             parent.mainWindowParent.dzialCallBack(getWybranyDzial());
             parent.dispose();
            }
        });
        add(wyslijButton, gbc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the wybranyDzial
     */
    public int getWybranyDzial() {
        return wybranyDzial;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
